# Copyright 2026 Charmer
# See LICENSE file for licensing details.

[tox]
no_package = True
skip_missing_interpreters = True
env_list = format, lint, unit
min_version = 4.0.0

[vars]
src_path = {tox_root}/src
tests_path = {tox_root}/tests
all_path = {[vars]src_path} {[vars]tests_path}

[testenv]
deps =
    -r{tox_root}/requirements.txt
set_env =
    PYTHONPATH = {tox_root}/lib:{[vars]src_path}
    PYTHONBREAKPOINT=pdb.set_trace
    PY_COLORS=1
pass_env =
    PYTHONPATH
    CHARM_BUILD_DIR
    MODEL_SETTINGS

[testenv:format]
description = Apply coding style standards to code
deps =
    {[testenv]deps}
    ruff
commands =
    ruff format {[vars]all_path}
    ruff check --fix {[vars]all_path}

[testenv:lint]
description = Check code against coding style standards, and static checks
deps =
    {[testenv]deps}
    codespell
    pyright
    pytest
    jubilant>=1.8,<2
    pytest-jubilant>=2.0.1,<3
    ops[testing]
    ruff
commands =
    codespell {tox_root}
    ruff check {[vars]all_path}
    ruff format --check --diff {[vars]all_path}
    pyright {posargs}

[testenv:unit]
description = Run unit tests
deps =
    {[testenv]deps}
    coverage[toml]
    ops[testing]
    pytest
commands =
    coverage run --source={[vars]src_path} -m pytest \
        -v \
        -s \
        --tb native \
        {[vars]tests_path}/unit \
        {posargs}
    coverage report

[testenv:integration]
description = Run integration tests
deps =
    {[testenv]deps}
    jubilant>=1.8,<2
    pytest
    pytest-jubilant>=2.0.1,<3
pass_env =
    # The integration tests don't pack the charm. If CHARM_PATH is set, the tests deploy the
    # specified .charm file. Otherwise, the tests look for a .charm file in the project dir.
    CHARM_PATH
commands =
    pytest \
        -v \
        -s \
        --tb native \
        --log-cli-level=INFO \
        {[vars]tests_path}/integration \
        {posargs}
